apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wsi
  name: order
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
      annotations:
        kubectl.kubernetes.io/default-container: order
    spec:
      serviceAccountName: "dynamodb"
      containers:
        - name: order
          image: 702661606257.dkr.ecr.ap-northeast-2.amazonaws.com/order-ecr:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.5"
              memory: 0.5G
          env:
            - name: AWS_REGION
              value: ap-northeast-2

        - name: fluent-bit
          image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
          imagePullPolicy: Always
          env:
            - name: AWS_REGION
              value: ap-northeast-2
            - name: CLUSTER_NAME
              value: wsi-eks-cluster
            - name: HTTP_SERVER
              value: "On"
            - name: HTTP_PORT
              value: "2020"
            - name: CI_VERSION
              value: "k8s/1.3.23"
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config