apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore  #secretstore이름
  namespace: wsi
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: secretmanager #service account 이름