apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: wsi
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: rds-secret
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: "rds!db-3baf372b-e308-43ac-ae27-ef1f97aab245"
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: "rds!db-3baf372b-e308-43ac-ae27-ef1f97aab245"
      property: password