apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit
  namespace: logging
rules:
- apiGroups: ["*"]
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit
roleRef:
  kind: ClusterRole
  name: fluentbit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentbit-irsa
  namespace: logging

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: logging
  labels:
    k8s-app: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      serviceAccountName: fluentbit-irsa
      containers:
      - name: fluentbit
        image: fluent/fluent-bit:latest
        ports:
        - containerPort: 2020
          name: api
        - containerPort: 24224
          name: forward
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config
        configMap:
          name: fluentbit-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name        tail
        Path        /var/log/containers/product*.log
        Parser      docker
        Tag         product

    [INPUT]
        Name        tail
        Path        /var/log/containers/customer*.log
        Parser      docker
        Tag         customer

    [OUTPUT]
        Name cloudwatch_logs
        Match   product
        region ap-northeast-2
        log_group_name /wsi/webapp/product
        log_stream_prefix from-fluent-bit-
        auto_create_group On

    [OUTPUT]
        Name cloudwatch_logs
        Match   customer
        region ap-northeast-2
        log_group_name /wsi/webapp/customer
        log_stream_prefix from-fluent-bit-
        auto_create_group On

  parsers.conf: |
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On
        Decode_Field_As   escaped_utf8    log
