apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: wsi
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: rds-secret
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: "rds!cluster-4cba8753-f0df-4a66-b196-5d7022236fe6"
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: "rds!cluster-4cba8753-f0df-4a66-b196-5d7022236fe6"
      property: password