apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eks-secret-store 
  namespace: wsi
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: dbaccess