apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wsc2024-eks-cluster
  region: us-east-1 
  version: "1.29"

iam:
  withOIDC: true

secretsEncryption:
  keyARN: arn:aws:kms:us-east-1:702661606257:key/a52d4964-f9fc-429a-89cd-c4409f4b280e

vpc:
  subnets:
    private:
      us-east-1a:
        id: subnet-0bc715b9079b75cfe
      us-east-1b:
        id: subnet-0adb0828c3ec1e4cc

managedNodeGroups:
  - name: wsc2024-db-application-ng
    taints:
      - key: wsi
        value: "app"
        effect: NoSchedule
    minSize: 2
    desiredCapacity: 2
    maxSize: 10
    labels:
      app: db
    instanceType: t3.medium
    instanceName: wsc2024-db-application-node
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true
  - name: wsc2024-other-ng
    minSize: 2
    desiredCapacity: 2
    maxSize: 10
    labels:
      app: other
    instanceType: t3.medium
    instanceName: wsc2024-other-node
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    