apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wsi
  name: product
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: product
  template:
    metadata:
      labels: 
        app: product
      annotations:
        kubectl.kubernetes.io/default-container: product
    spec:
      tolerations:
        - key: wsi
          operator: Equal
          value: "app"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: wsi
                operator: In
                values:
                  - "app"
      serviceAccountName: "fluent-bit" 
      containers:
      - name: product
        image: 702661606257.dkr.ecr.ap-northeast-2.amazonaws.com/product-ecr:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 200m
        env:
          - name: MYSQL_USER #환경변수 이름
            valueFrom:
              secretKeyRef:
                name: product #eks secret 이름
                key: MYSQL_USER  #eks secret 안에 있는 값중에 어떤 key 인지 지정
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: product
                key: MYSQL_PASSWORD
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: product
                key: MYSQL_HOST
          - name: MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: product
                key: MYSQL_PORT
          - name: MYSQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: product
                key: MYSQL_DBNAME

      - name: fluent-bit
        image: public.ecr.aws/aws-observability/aws-for-fluent-bit:stable
        imagePullPolicy: Always
        env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: fluent-bit-cluster-info
                  key: logs.region
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: fluent-bit-cluster-info
                  key: cluster.name
            - name: HTTP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: fluent-bit-cluster-info
                  key: http.server
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: fluent-bit-cluster-info
                  key: http.port
            - name: READ_FROM_HEAD
              valueFrom:
                configMapKeyRef:
                  name: fluent-bit-cluster-info
                  key: read.head
            - name: READ_FROM_TAIL
              valueFrom:
                configMapKeyRef:
                  name: fluent-bit-cluster-info
                  key: read.tail
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: CI_VERSION
              value: "k8s/1.3.23"
        resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
        volumeMounts:
        - name: fluentbitstate
          mountPath: /var/fluent-bit/state
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: fluentbitstate
        hostPath:
          path: /var/fluent-bit/state
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config