apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product
  namespace: wsi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore  #secret store 이름
    kind: SecretStore
  target:
    name: product  #eks secret 만들어질 이름
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_USER  #eks secret의 key
    remoteRef:
      key: product #AWS Secrets Manager secret 이름
      property: MYSQL_USER #AWS Secrets Manager secret key
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: product
      property: MYSQL_PASSWORD
  - secretKey: MYSQL_HOST
    remoteRef:
      key: product
      property: MYSQL_HOST
  - secretKey: MYSQL_PORT
    remoteRef:
      key: product
      property: MYSQL_PORT
  - secretKey: MYSQL_DBNAME
    remoteRef:
      key: product
      property: MYSQL_DBNAME