apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wsc2024
  name: order-deploy
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      tolerations:
        - key: wsi
          operator: Equal
          value: "app"
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                  - "db"
      serviceAccountName: "dynamodbaccess" 
      containers:
      - name: order
        image: 702661606257.dkr.ecr.us-east-1.amazonaws.com/order-repo:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 200m
        env:
          - name: AWS_REGION
            value: us-east-1
